default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: demo
  password: demo@12345
  host: localhost
  port: 3306

development:
  <<: *default
  database: quanlysinhvien

test:
  <<: *default
  database: your_app_name_test

production:
  <<: *default
  database: your_app_name_production
  username: your_mysql_production_username
  password: your_mysql_production_password
  host: your_mysql_production_host
  port: your_mysql_production_port
